swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains users API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Accounts listing array
      description: Listing all transactions in an array
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions listing array
      description: Listing all transactions
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/id:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction filtered by ID
      description: API for fetching a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Transaction ID
          required: true
          schema:
            $ref: '#/definitions/TransactionID'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction filtered by ID
      description: API for updating a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Account:
    properties:
      id:
        type: string
        description: Bank account id
      amount:
        type: number
        description: Bank account amount
  TransactionsResponse:
    type: object
    properties:
      id:
        type: number
      transaction:
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
          type:
            type: string
          categorie:
            type: string
          note:
            type: string
  AccountResponse:
    properties:
      id:
        type: string
        description: Bank account id
      amount:
        type: number
        description: Bank account amount
  Transaction:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      categorie:
        type: string
      note:
        type: string
  TransactionID:
    properties:
      id:
        type: number
        description: transaction id
